### ISSUE TITLE
Поправить базовый Input

### ISSUE THREAD

**Issue by Fr0stmourne** [Olga-Skoroded/toxin-group-project#84]
- блок ошибки под инпутом не должен увеличивать его размер, иначе в компоненте подписки неудобно растягивать на всю высоту поля кнопку отправки
- нужно поправить шрифт текста, сейчас там плейсхолдер с нужным шрифтом, а обычный вводимый текст  - Arial

**Comment by AkhmadBabaev** [comment]
Установи ещё курсор pointer для label.
